# permissions for end users to view prefectenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prefectenvironment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prefect-operator
    app.kubernetes.io/part-of: prefect-operator
    app.kubernetes.io/managed-by: kustomize
  name: prefectenvironment-viewer-role
rules:
- apiGroups:
  - mlops.aigency.com
  resources:
  - prefectenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.aigency.com
  resources:
  - prefectenvironments/status
  verbs:
  - get
