---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mlops.aigency.com
  resources:
  - prefectenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.aigency.com
  resources:
  - prefectenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - mlops.aigency.com
  resources:
  - prefectenvironments/status
  verbs:
  - get
  - patch
  - update
