apiVersion: mlops.aigency.com/v1alpha1
kind: PrefectEnvironment
metadata:
  labels:
    app.kubernetes.io/name: prefectenvironment
    app.kubernetes.io/instance: prefectenvironment-sample
    app.kubernetes.io/part-of: prefect-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: prefect-operator
  name: prefectenvironment-sample
spec:
  # TODO(user): Add fields here
